// USERINFO
export const UPDATE_USERINFO = "UPDATE_USERINFO"

// NOTIFICATIONINFO
export const GET_NOTIFICATION = "GET_NOTIFICATION"
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS"
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION"
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION"
export const ADD_NOTIFICATION = "ADD_NOTIFICATION"

// NOTIFICATIONCOUNT
export const ADD_NOTIFICATIONCOUNT = "ADD_NOTIFICATIONCOUNT"
export const REDUCE_NOTIFICATIONCOUNT = "REDUCE_NOTIFICATIONCOUNT"
export const UPDATE_NOTIFICATIONCOUNT = "UPDATE_NOTIFICATIONCOUNT"

// VIDEO
export const GET_VIDEOLIST = "GET_VIDEOLIST"
export const ADD_VIDEOLIST = "ADD_VIDEOLIST"

export default {
    GET_NOTIFICATION,
    GET_NOTIFICATIONS,
    UPDATE_NOTIFICATION,
    REMOVE_NOTIFICATION,
    ADD_NOTIFICATION,
    ADD_NOTIFICATIONCOUNT,
    REDUCE_NOTIFICATIONCOUNT,
    UPDATE_NOTIFICATIONCOUNT
}
